version: "3.7"

services:
  appdb:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: edu_app
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "YES"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - appdb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - db

  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - vendor-data:/app/vendor
    ports:
      - "8000:8000"
      - "587:587"
    networks:
      - app-network
      - db
    depends_on:
      appdb:
        condition: service_healthy
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
  db:

volumes:
  vendor-data:
  backend:
  appdb:
    driver: local
  initdb:
